//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnet_mvc_authentication_membership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTask
    {
        public int TaskId { get; set; }
        public string TaskSummary { get; set; }
        public string TaskDesc { get; set; }
        public Nullable<System.DateTime> TaskDue { get; set; }
        public string TaskReporter { get; set; }
        public string TaskAssignee { get; set; }
        public Nullable<int> TaskPriority { get; set; }
    
        public virtual Priority Priority { get; set; }
    }
}
